name: Update README with latest version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest version tag
        id: get_version
        run: echo "VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Update README with latest version
        run: |
          sed -i "s|Latest Version: .*|Latest Version: **${{ env.VERSION }}**|" README.md

      - name: Commit changes
        run: |
          git config --local user.email "jusho@gmail.com"
          git config --local user.name "ju8sho"
          git add README.md
          git commit -m "Update README with latest version"
          git push
